use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::fs;
use std::net::IpAddr;
use std::path::{Path, PathBuf};

pub mod egress;

pub use crate::types::PortForward;
pub use egress::{EgressPolicy, EgressProxyServer, LlmTokenBudget, SecretSubstitution};

/// Network mode for the microVM provider abstraction.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub enum NetworkMode {
    /// In-process Transparent Socket Impersonation (TSI) built into libkrun.
    /// Exposes ports according to the port map without needing root.
    #[default]
    Tsi,
    /// Virtio-net interface connected to an external user-space stream socket (e.g. gvproxy, passt, or CNI socket).
    UnixStream(PathBuf),
    /// Virtio-net connected to a Kubernetes CNI network namespace (e.g., via passt/veth or netns socket).
    Cni {
        netns: PathBuf,
        socket_path: Option<PathBuf>,
    },
    /// Complete air-gapped isolation: no network interfaces, only loopback (lo).
    None,
}

impl NetworkMode {
    pub fn is_cni(&self) -> bool {
        matches!(self, Self::Cni { .. })
    }

    pub fn netns_path(&self) -> Option<&Path> {
        match self {
            Self::Cni { netns, .. } => Some(netns.as_path()),
            _ => None,
        }
    }

    pub fn unix_socket_path(&self) -> Option<&Path> {
        match self {
            Self::UnixStream(p) => Some(p.as_path()),
            Self::Cni { socket_path, .. } => socket_path.as_deref(),
            _ => None,
        }
    }
}

pub struct DnsConfig;

impl DnsConfig {
    /// Parses DNS input strings which can be comma-separated, semicolon-separated,
    /// or individual IPs (e.g. `--dns 8.8.8.8,1.1.1.1`).
    pub fn parse_dns_flags(inputs: &[String]) -> Vec<String> {
        let mut servers = Vec::new();
        for input in inputs {
            for part in input.split([',', ';']) {
                let trimmed = part.trim();
                if !trimmed.is_empty() {
                    servers.push(trimmed.to_string());
                }
            }
        }
        servers
    }

    /// Resolves active nameservers. If custom nameservers are provided, they are used.
    /// Otherwise, checks host `/etc/resolv.conf`, filters out loopback stubs (127.0.0.1, 127.0.0.53)
    /// which would fail inside the guest, and falls back to resilient defaults ("8.8.8.8", "1.1.1.1").
    pub fn resolve_nameservers(custom_dns: &[String]) -> Vec<String> {
        let parsed = Self::parse_dns_flags(custom_dns);
        if !parsed.is_empty() {
            return parsed;
        }

        // Try reading host resolv.conf
        if let Ok(content) = fs::read_to_string("/etc/resolv.conf") {
            let mut host_servers = Vec::new();
            for line in content.lines() {
                let trimmed = line.trim();
                if trimmed.starts_with("nameserver ") {
                    let ip_str = trimmed.trim_start_matches("nameserver ").trim();
                    if let Ok(ip) = ip_str.parse::<IpAddr>() {
                        if !ip.is_loopback() {
                            host_servers.push(ip.to_string());
                        }
                    }
                }
            }
            if !host_servers.is_empty() {
                return host_servers;
            }
        }

        // Standard default fallback DNS servers
        vec!["8.8.8.8".to_string(), "1.1.1.1".to_string()]
    }

    /// Injects /etc/resolv.conf, /etc/hosts, and /etc/hostname into the guest rootfs.
    pub fn write_network_files(
        rootfs: &Path,
        hostname: &str,
        nameservers: &[String],
    ) -> Result<()> {
        let etc_dir = rootfs.join("etc");
        fs::create_dir_all(&etc_dir)
            .with_context(|| format!("Failed to create {}", etc_dir.display()))?;

        // 1. Write /etc/resolv.conf
        let mut resolv = String::from("# Generated by krun-microvm (Autonomous Resilient DNS)\n");
        for ns in nameservers {
            resolv.push_str(&format!("nameserver {}\n", ns));
        }
        resolv.push_str("options edns0 trust-ad\n");
        let resolv_path = etc_dir.join("resolv.conf");
        fs::write(&resolv_path, resolv)
            .with_context(|| format!("Failed to write {}", resolv_path.display()))?;

        // 2. Write /etc/hosts
        let hosts = format!(
            "127.0.0.1 localhost {}\n::1 localhost ip6-localhost ip6-loopback\n",
            hostname
        );
        let hosts_path = etc_dir.join("hosts");
        fs::write(&hosts_path, hosts)
            .with_context(|| format!("Failed to write {}", hosts_path.display()))?;

        // 3. Write /etc/hostname
        let hostname_path = etc_dir.join("hostname");
        fs::write(&hostname_path, format!("{}\n", hostname))
            .with_context(|| format!("Failed to write {}", hostname_path.display()))?;

        Ok(())
    }

    /// Injects HTTP/HTTPS proxy configuration into guest rootfs (/etc/environment and /etc/profile.d/krun_proxy.sh).
    pub fn inject_proxy_environment(rootfs: &Path, proxy_url: &str) -> Result<()> {
        let etc_dir = rootfs.join("etc");
        fs::create_dir_all(&etc_dir)
            .with_context(|| format!("Failed to create {}", etc_dir.display()))?;

        // 1. Append to /etc/environment
        let env_path = etc_dir.join("environment");
        let mut current_env = fs::read_to_string(&env_path).unwrap_or_default();
        let proxy_lines = format!(
            "\nHTTP_PROXY={proxy_url}\nHTTPS_PROXY={proxy_url}\nhttp_proxy={proxy_url}\nhttps_proxy={proxy_url}\nALL_PROXY={proxy_url}\nNO_PROXY=localhost,127.0.0.1\nno_proxy=localhost,127.0.0.1\n"
        );
        current_env.push_str(&proxy_lines);
        fs::write(&env_path, current_env)?;

        // 2. Write /etc/profile.d/krun_proxy.sh
        let profile_dir = etc_dir.join("profile.d");
        fs::create_dir_all(&profile_dir)?;
        let profile_script = format!(
            "export HTTP_PROXY=\"{proxy_url}\"\nexport HTTPS_PROXY=\"{proxy_url}\"\nexport http_proxy=\"{proxy_url}\"\nexport https_proxy=\"{proxy_url}\"\nexport ALL_PROXY=\"{proxy_url}\"\nexport NO_PROXY=\"localhost,127.0.0.1\"\nexport no_proxy=\"localhost,127.0.0.1\"\n"
        );
        fs::write(profile_dir.join("krun_proxy.sh"), profile_script)?;

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn test_parse_dns_flags_comma_and_semicolon() {
        let inputs = vec![
            "8.8.8.8,1.1.1.1".to_string(),
            "9.9.9.9;149.112.112.112".to_string(),
        ];
        let res = DnsConfig::parse_dns_flags(&inputs);
        assert_eq!(
            res,
            vec!["8.8.8.8", "1.1.1.1", "9.9.9.9", "149.112.112.112"]
        );
    }

    #[test]
    fn test_resolve_nameservers_custom() {
        let custom = vec!["1.0.0.1".to_string()];
        let res = DnsConfig::resolve_nameservers(&custom);
        assert_eq!(res, vec!["1.0.0.1"]);
    }

    #[test]
    fn test_write_network_files() {
        let dir = tempdir().unwrap();
        let nameservers = vec!["8.8.8.8".to_string(), "1.1.1.1".to_string()];
        DnsConfig::write_network_files(dir.path(), "my-test-vm", &nameservers).unwrap();

        let resolv = fs::read_to_string(dir.path().join("etc/resolv.conf")).unwrap();
        assert!(resolv.contains("nameserver 8.8.8.8"));
        assert!(resolv.contains("nameserver 1.1.1.1"));

        let hosts = fs::read_to_string(dir.path().join("etc/hosts")).unwrap();
        assert!(hosts.contains("127.0.0.1 localhost my-test-vm"));

        let hostname = fs::read_to_string(dir.path().join("etc/hostname")).unwrap();
        assert_eq!(hostname.trim(), "my-test-vm");
    }

    #[test]
    fn test_network_mode_cni() {
        let mode = NetworkMode::Cni {
            netns: PathBuf::from("/proc/1234/ns/net"),
            socket_path: Some(PathBuf::from("/run/cni-krun.sock")),
        };
        assert!(mode.is_cni());
        assert_eq!(mode.netns_path(), Some(Path::new("/proc/1234/ns/net")));
        assert_eq!(
            mode.unix_socket_path(),
            Some(Path::new("/run/cni-krun.sock"))
        );
    }
}
